### ISSUE TITLE
Replace current time with latest tweet/mention/etc.

### ISSUE THREAD

**Issue by adamralph** [Particular/HashBus#100]
E.g. instead of the current date time followed by "Refreshing..." we have something like:

> Total tweets: 1,724 from 17.11.15 18:17:41 to 19.11.15 09:07:59

**Comment by adamralph** [comment]
Thoughts?

**Comment by adamralph** [comment]
Might be difficult to fit into the screen... may have to juggle things round a bit...

**Comment by Farol** [comment]
@adamralph 
What do you think of that:
![image](https://cloud.githubusercontent.com/assets/604826/11660741/e0805050-9dce-11e5-91e7-5c87e6443812.png)

**Comment by adamralph** [comment]
@Farol that looks good!

Some small points:
* We can remove "Since"
* Obviously something weird happened with the indent on the last line, so that needs fixing.
