### ISSUE TITLE
move the transport to Azure ServiceBus

### ISSUE THREAD

**Issue by mauroservienti** [Particular/HashBus#103]
* in order to be able to deploy each endpoint as a worker
* to easily scale out

Related to #45

**Comment by adamralph** [comment]
How will this affect development on a plane? Can I still run everything offline? Or do we need to make it configurable?

**Comment by adamralph** [comment]
I'm not convinced about this. Seems more trouble than it's worth. @mauroservienti thoughts?

**Comment by mauroservienti** [comment]
Agree, the only good reason is if we want to demo how powerful Azure scale out options are, however that means tight all the endpoints to the Azure infrastructure running each of them as a separate worker/web role. But even if I can think to the highest possible throughput the effort still is not worth.
