### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by adamralph** [Particular/HashBus#112]

**Comment by adamralph** [comment]
I think we should do this before NDC Sydney. It's bad that we advertise this as open source and provide the URL to the repo but it doesn't even have a license.

@Particular/hashbus-maintainers what kind of license do we want? Is permissive (e.g. MIT, Apache) OK?

**Comment by WojcikMike** [comment]
I would go with MIT. I saw it being used in some of the projects in Particular Labs:
https://github.com/ParticularLabs/APIComparer/blob/master/License.txt
