### ISSUE TITLE
When a non-default hashtag is used, the title is still BuildStuffUA

### ISSUE THREAD

**Issue by adamralph** [Particular/HashBus#115]
e.g.

![image](https://cloud.githubusercontent.com/assets/677704/11361194/fe22b56a-928b-11e5-87b8-ca1b48781e1f.png)

**Comment by adamralph** [comment]
@pgermishuys any interest? :wink:

**Comment by pgermishuys** [comment]
Sure, need to get off plane and then ill have a look
